name: Ubuntu CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test_cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install CMake and PKG-Config
        run: sudo apt-get install cmake pkg-config
      - name: Build Application
        run: cd cpp && ./build.sh
      - name: Run Tests
        run: cd cpp && ./test.sh
